name: datadog-actions-metrics
description: submit metrics of GitHub Actions to Datadog
inputs:
  github-token:
    description: GitHub token
    default: ${{ github.token }}
    required: true
  datadog-api-key:
    description: Datadog API key (dry-run if not set)
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
